# Generated by Django 2.1.7 on 2019-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applicantdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantdetails',
            name='visible',
        ),
        migrations.AddField(
            model_name='user',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
