# Generated by Django 2.1.7 on 2019-03-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190317_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantdetails',
            name='applicant',
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.DeleteModel(
            name='ApplicantDetails',
        ),
    ]
