# Generated by Django 2.1.7 on 2019-03-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='user',
        ),
    ]
